apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test
    azure-key-vault-env-injection: enabled
---
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
