apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: kratos-db
  namespace: ory
spec:
  description: Kratos db
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3

  storage:
    size: 200Mi
