kratos:
  config:
    dsn: postgres://app:9RXphWTqdfXxfdmjNt5kgbJFpOtC06oViL8tWe1cznHmAdrFrGj7IN5oVVB09TiW@kratos-db-rw:5432/app
    # secrets:
    #   default:
    #     - dolore occaecat nostrud Ut
    #     - sit et commodoaute ut voluptate consectetur Duis
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json
    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
    selfservice:
      default_browser_return_url: http://127.0.0.1:4455/
  automigration:
    enabled: true
  identitySchemas:
    "identity.default.schema.json": |
      {
        "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "title": "E-Mail",
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "recovery": {
                    "via": "email"
                  },
                  "verification": {
                    "via": "email"
                  }
                }
              }
            },
            "required": [
              "email"
            ],
            "additionalProperties": false
          }
        }
      }
deployment:
  extraEnv:
    # - name: DSN
    #   value: "postgres://${PG_USER}:${PG_SECRET}@postgresd:5432/kratos?sslmode=${SSL_MODE}&max_conns=20&max_idle_conns=4"
    - name: SERVE_PUBLIC_BASE_URL
      value: "https://test.mischa.dk/.ory/kratos/public/"
    - name: SELFSERVICE_WHITELISTED_RETURN_URLS
      value: "https://test.mischa.dk/ss/auth/hydra/login,https://test.mischa.dk/,https://test.mischa.dk/"
    - name: SELFSERVICE_DEFAULT_BROWSER_RETURN_URL
      value: "https://test.mischa.dk"
    - name: SELFSERVICE_FLOWS_SETTINGS_UI_URL
      value: "https://test.mischa.dk/ss/settings"
    - name: SELFSERVICE_FLOWS_VERIFICATION_UI_URL
      value: "https://test.mischa.dk/ss/verify"
    - name: SELFSERVICE_FLOWS_VERIFICATION_AFTER_DEFAULT_BROWSER_RETURN_URL
      value: "https://test.mischa.dk"
    - name: SELFSERVICE_FLOWS_RECOVERY_UI_URL
      value: "https://test.mischa.dk/ss/recovery"
    - name: SELFSERVICE_FLOWS_LOGOUT_UI_URL
      value: "https://test.mischa.dk/ss/logout"
    - name: SELFSERVICE_FLOWS_LOGIN_UI_URL
      value: "https://test.mischa.dk/ss/auth/login"
    - name: SELFSERVICE_FLOWS_REGISTRATION_UI_URL
      value: "https://test.mischa.dk/ss/auth/registration"
    - name: SELFSERVICE_FLOWS_ERROR_UI_URL
      value: "https://test.mischa.dk/ss/error"
    # - name: COURIER_SMTP_CONNECTION_URI
    #   value: "${COURIER_SMTP_CONNECTION_URI}"
    - name: SQA_OPT_OUT
      value: "true"
