---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: prometheus-user
spec:
  vault:
    name: {{ .Values.keyVault }}
    object:
      name: prometheus-user
      type: secret
  output:
    secret:
      name: grafana-agent-credentials-akv2k8s
      dataKey: prometheus-user
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: prometheus-password
spec:
  vault:
    name: {{ .Values.keyVault }}
    object:
      name: prometheus-password
      type: secret
  output:
    secret:
      name: grafana-agent-credentials-akv2k8s
      dataKey: prometheus-password
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: prometheus-host
spec:
  vault:
    name: {{ .Values.keyVault }}
    object:
      name: prometheus-host
      type: secret
  output:
    secret:
      name: grafana-agent-credentials-akv2k8s
      dataKey: prometheus-host
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: loki-user
spec:
  vault:
    name: {{ .Values.keyVault }}
    object:
      name: loki-user
      type: secret
  output:
    secret:
      name: grafana-agent-credentials-akv2k8s
      dataKey: loki-user
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: loki-password
spec:
  vault:
    name: {{ .Values.keyVault }}
    object:
      name: loki-password
      type: secret
  output:
    secret:
      name: grafana-agent-credentials-akv2k8s
      dataKey: loki-password
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: loki-host
spec:
  vault:
    name: {{ .Values.keyVault }}
    object:
      name: loki-host
      type: secret
  output:
    secret:
      name: grafana-agent-credentials-akv2k8s
      dataKey: loki-host
---
