apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
# Example of PostgreSQL cluster
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: postgres-dev
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi
