apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-frontend
    tier: frontend
  name: httpd-frontend
  namespace: kedapoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: httpd-frontend
        tier: frontend
    spec:
      containers:
        - image: httpd
          name: httpd
          env:
            - name: PG_PASSWORD
              value: ohfLnipJ4lgJgTi64NpfTKC21U7SV8FPby2AVtMD1yQYIiMLF2HnZVYdwPJOgHWR
