apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-frontend
    tier: frontend
  name: httpd-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: httpd-frontend
        tier: frontend
    spec:
      containers:
        - image: httpd
          name: httpd
          env:
            - name: PG_PASSWORD
              value: TCFHK8FjQpCQKGeBXwX9zRrb7YCXykB5Xmz0r7sIxxqDaDWUAZuaPj6Ma18L6qpf
