apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homarr
  name: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
        - name: homarr
          image: ghcr.io/ajnart/homarr:0.14.5

          ports:
            - containerPort: 7575
              protocol: TCP
