apiVersion: v2
name: k8s-monitoring
version: 1.0.0
description: This chart deploys the k8s-monitoring chart with custom secrets
dependencies:
  - name: k8s-monitoring
    version: 0.5.1
    repository: https://grafana.github.io/helm-charts/
