keyVault: kv-dev-weu-001

k8s-monitoring:
  cluster:
    name: aks-kv-dev

  externalServices:
    prometheus:
      hostKey: prometheus-host
      basicAuth:
        usernameKey: prometheus-user
        passwordKey: prometheus-password

      secret:
        create: false
        name: grafana-agent-credentials-akv2k8s
        namespace: k8s-monitoring

    loki:
      hostKey: loki-host
      basicAuth:
        usernameKey: loki-user
        passwordKey: loki-password

      secret:
        create: false
        name: grafana-agent-credentials-akv2k8s
        namespace: k8s-monitoring

  extraConfig: |-
    logging {
      level  = "info"
      format = "logfmt"
    }
