kratosPublicUrl: "http://test.mischa.dk"
kratosBrowserUrl: "http://test.mischa.dk:4433/"

deployment:
  extraEnv:
    - name: COOKIE_SECRET
      value: ab318v45
    - name: CSRF_COOKIE_NAME
      value: ory_csrf_ui
    - name: CSRF_COOKIE_SECRET
      value: mischaisthebestlol
