apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  # labels:
  #   io.kompose.service: mealie-data
  name: mealie-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
# status: {}
