apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-backend
  name: httpd-backend
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: httpd-backend
  template:
    metadata:
      labels:
        app: httpd-backend
        tier: backend
    spec:
      containers:
        - image: ghcr.io/mytest/httpd:v0.0.0
          name: httpd
