apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
  namespace: ory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - image: sekvensanalyseplatform/sap-web:431
          name: web-app
          ports:
            - containerPort: 3333
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3333"
