apiVersion: v1
kind: Namespace
metadata:
  name: blobpoc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-backend
    tier: backend
  name: httpd-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-backend
      tier: backend
  template:
    metadata:
      labels:
        app: httpd-backend
        tier: backend
    spec:
      containers:
        - image: httpd
          name: httpd
          volumeMounts:
            - name: blob01
              mountPath: "/mnt/blob"
              readOnly: false
      volumes:
        - name: blob01
          persistentVolumeClaim:
            claimName: pvc-blob
