name: replace tag

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq eval '.spec.template.spec.containers[0].image = "ghcr.io/mytest/httpd:v0.0.1"' -i ./kubernetes/deployments/test.yaml

      - name: push
        uses: actions-x/commit@v6
        with:
          email: me@example.com
          name: GitHub Actions Autocommitter
          branch: main
